In [1]:
import numpy as np
import pandas as pd
from influxdb import InfluxDBClient

In [2]:
# Connect to InfluxDB and fetch data
client = InfluxDBClient(host='localhost', port=8086)
client.switch_database('ISS')

In [3]:
# Query to the Database for one measurement

#query1 = 'SELECT * FROM "DE1Thing_HMD8310"'
#query1 = 'SELECT * FROM "DE1Thing_HMD8310" WHERE time >= \'2022-08-29T23:28:00Z\' AND time < \'2023-01-26T08:00:00Z\''
query1 = 'SELECT * FROM "EP_Battery.Thing_HMD8310"'
results1 = client.query(query1)
EP_Battery_Thing_HMD8310 = pd.DataFrame.from_records(results1.get_points())

print(EP_Battery_Thing_HMD8310.shape)
EP_Battery_Thing_HMD8310.head(5)

(273961, 110)

,time,AVG_PACK_SOC,AvgSOC,AvgSOH,BATT_PACK_1_DISCONN,BATT_PACK_1_FAULT,BATT_PACK_1_WARN,BATT_PACK_2_DISCONN,BATT_PACK_2_FAULT,BATT_PACK_2_WARN,...,PACK_1_STATUS,PACK_2_STATUS,PACK_3_STATUS,PACK_4_STATUS,PACK_5_STATUS,PACK_6_STATUS,PACK_7_STATUS,RunningState,Voltage,valuestreamname
0,2022-08-30T00:00:00Z,NaN,77.0,100.0,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,900.0,ISS.Onshore.Model.VS
1,2022-08-30T00:01:00Z,NaN,77.0,100.0,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,900.0,ISS.Onshore.Model.VS
2,2022-08-30T00:02:00Z,NaN,77.0,100.0,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,900.0,ISS.Onshore.Model.VS
3,2022-08-30T00:03:00Z,NaN,77.0,100.0,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,900.0,ISS.Onshore.Model.VS
4,2022-08-30T00:04:00Z,NaN,77.0,100.0,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,900.0,ISS.Onshore.Model.VS

In [ ]:
EP_Battery_Thing_HMD8310.to_csv('EP_Battery_Thing_HMD8310.csv', index=False)